version: "3.8"

services:
  postgres-kc:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kc-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-kc-data:/var/lib/postgres/data
    networks:
      - school-flow-networks

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: 12345
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-kc
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 1234
      KC_DB_URL_DATABASE: kc-db
      KC_DB_SCHEMA: public
    command: ["start-dev", "--import-realm"]
    depends_on:
      - postgres-kc
    volumes:
      - kc-data:/opt/jboss/keycloak/standalone/data
    networks:
      - school-flow-networks


  mongodb-student:
    image: mongo
    container_name: mongodb-student
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-user-data:/data/db
    networks:
      - school-flow-networks

  mongodb-professor:
    image: mongo
    container_name: mongodb-professor
    ports:
      - "27018:27017"
    expose:
      - "27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: PROPERTY-DB
    volumes:
      - mongo-property-data:/data/db
    networks:
      - school-flow-networks

  mongo-expres-user:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-user
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - school-flow-networks

  mongo-expres-property:
    image: mongo-express
    ports:
      - "8082:8081"
    expose:
      - "8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-property
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - school-flow-networks

networks:
  school-flow-networks:
    driver: bridge

volumes:
  mongo-user-data:
  mongo-property-data:
  postgres-kc-data:
  kc-data:
