import { faBell, faCircleCheck, faCommentDots, faPenToSquare } from "@fortawesome/free-regular-svg-icons";
import {
  faBook,
  faBookOpenReader,
  faCalendarDays,
  faCartPlus,
  faCartShopping,
  faChalkboardTeacher,
  faChevronRight,
  faCircleQuestion,
  faCircleUser,
  faGauge,
  faGavel,
  faGear, faGraduationCap, faMagnifyingGlass,
  faMoneyCheckDollar,
  faPlus,
  faRightFromBracket,
  faSchoolFlag,
  faTrashCan,
  faUser,
  faWallet,
  IconDefinition
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcons: IconDefinition[]= [
  faRightFromBracket,
  faGear,
  faCircleUser,
  faCircleQuestion,
  faMagnifyingGlass,
  faCartPlus,
  faCartShopping,
  faChevronRight,
  faGauge,
  faUser,
  faSchoolFlag,
  faGraduationCap,
  faChalkboardTeacher,
  faCalendarDays,
  faMoneyCheckDollar,
  faBookOpenReader,
  faWallet,
  faBook,
  faGavel,
  faBell,
  faCommentDots,
  faCircleCheck,
  faPlus,
  faPenToSquare,
  faTrashCan

]
